build: switching back to ubi9-minimal base image
due to issues with pulling the latest version of ubi10-micro in the CI/CD workflow
```
Trying to pull registry.access.redhat.com/ubi10/ubi-micro:latest...
Error: creating build container: copying system image from manifest list: Source image rejected: None of the signatures were accepted, reasons:
Signature for digest sha256:5941a9196571ade1959ca204e04acaf579418810fbc967b61436b26814ac5ce9 does not match;
Signature for digest sha256:5941a9196571ade1959ca204e04acaf579418810fbc967b61436b26814ac5ce9 does not match;
Signature for digest sha256:4fbdc7571973e6be219cba884e191294a2b8d8d1e0951cacb52cac3582c4e517 does not match;
Signature for digest sha256:4fbdc7571973e6be219cba884e191294a2b8d8d1e0951cacb52cac3582c4e517 does not match
```

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>